export enum HEADER_TYPES {
  DASHBOARD = "dashboard",
  ACCOUNTS = "accounts",
  TRANSFERS = "transfers",
  TRANSACTIONS = "transactions",
}
export enum ACCOUNT_TYPES {
  INVESTMENT_ACCOUNT = "INVESTMENT_ACCOUNT",
  DEPOSIT_ACCOUNT = "DEPOSIT_ACCOUNT",
  INTEREST_ACCOUNT = "INTEREST_ACCOUNT",
  EXCHANGE_ACCOUNT = "EXCHANGE_ACCOUNT",
}
export enum BANK_BRANCH_CODE {
  SUADIYE_BRANCH = "SUADIYE_BRANCH",
  CANAKKALE_BRANCH = "CANAKKALE_BRANCH",
  BORNOVA_BRANCH = "BORNOVA_BRANCH",
  BESIKTAS_BRANCH = "BESIKTAS_BRANCH",
  BALMUMCU_BRANCH = "BALMUMCU_BRANCH",
  KOSUYOLU_BRANCH = "KOSUYOLU_BRANCH",
}
