export enum TRANSACTION_RESULTS {
  SUCCESS = "SUCCESS",
  AWAITING_EVALUATION = "AWAITING_EVALUATION",
  REJECTED = "REJECTED",
  FAILED = "FAILED",
}
export enum EMPLOYEE_ACTIONS {
  CREATED = "CREATED",
  BANK_REGISTRATION = "BANK_REGISTRATION",
  CUSTOMER_ASSIGNMENT = "CUSTOMER_ASSIGNMENT",
  TRANSFER_APPROVAL_SUCCESS = "TRANSFER_APPROVAL_SUCCESS",
  TRANSFER_APPROVAL_FAIL = "TRANSFER_APPROVAL_FAIL",
}
