export enum USER_TYPES {
  BANK_DIRECTOR = "BANK_DIRECTOR",
  BANK_DEPARTMENT_DIRECTOR = "BANK_DEPARTMENT_DIRECTOR",
  BANK_CUSTOMER_REPRESENTATIVE = "BANK_CUSTOMER_REPRESENTATIVE",
  CUSTOMER = "CUSTOMER",
  ADMIN = "ADMIN",
}
