export enum CURRENCY_TYPES {
  EURO = "EURO",
  POUND_STERLING = "POUND_STERLING",
  SWISS_FRANC = "SWISS_FRANC",
  DOLLAR = "DOLLAR",
  CANADIAN_DOLLAR = "CANADIAN_DOLLAR",
  AUSTRALIAN_DOLLAR = "AUSTRALIAN_DOLLAR",
  YEN = "YEN",
  YUAN = "YUAN",
  WON = "WON",
  RENMINBI = "RENMINBI",
  RUSSIAN_RUBLE = "RUSSIAN_RUBLE",
  INDIAN_RUPEE = "INDIAN_RUPEE",
  BRAZILIAN_REAL = "BRAZILIAN_REAL",
  TURKISH_LIRA = "TURKISH_LIRA",
  SOUTH_AFRICAN_RAND = "SOUTH_AFRICAN_RAND",
  NEW_ZEALAND_DOLLAR = "NEW_ZEALAND_DOLLAR",
  SINGAPORE_DOLLAR = "SINGAPORE_DOLLAR",
  MALAYSIAN_RINGGIT = "MALAYSIAN_RINGGIT",
  HONG_KONG_DOLLAR = "HONG_KONG_DOLLAR",
  INDONESIAN_RUPIAH = "INDONESIAN_RUPIAH",
  PHILIPPINE_PESO = "PHILIPPINE_PESO",
  THAI_BAHT = "THAI_BAHT",
  VIETNAMESE_DONG = "VIETNAMESE_DONG",
  KUWAITI_DINAR = "KUWAITI_DINAR",
  SAUDI_RIYAL = "SAUDI_RIYAL",
  UAE_DIRHAM = "UAE_DIRHAM",
  ISRAELI_NEW_SHEKEL = "ISRAELI_NEW_SHEKEL",
  NORWEGIAN_KRONE = "NORWEGIAN_KRONE",
  SWEDISH_KRONA = "SWEDISH_KRONA",
  DANISH_KRONE = "DANISH_KRONE",
  POLISH_ZLOTY = "POLISH_ZLOTY",
  HUNGARIAN_FORINT = "HUNGARIAN_FORINT",
  CZECH_KORUNA = "CZECH_KORUNA",
}

export enum EVENT_RESULTS {
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
}
export enum AVAILABILITY_RESULT {
  ACCOUNT_IS_AVAILABLE = "AVAILABLE",
  ACCOUNT_IS_NOT_AVAILABLE = "NOT_AVAILABLE",
}
export enum ACCOUNT_STATUS {
  CREATED = 500,
  BANNED = 1000,
  AVAILABLE = 2000,
  IN_TRANSACTION = 2100,
  DELETED = 3000,
}
export enum ACCOUNT_TYPES {
  INVESTMENT = "INVESTMENT",
  DEPOSIT = "DEPOSIT",
}
export enum ACCOUNT_ACTIONS {
  CREATED = 1000,
  APPROVE_PENDING = 1900,
  APPROVED = 2000,
  TRANSFER_STARTED = 3200,
  MONEY_TRANSFERRED_TO_ACCOUNT = 3300,
  MONEY_TRANSFERRED_FROM_ACCOUNT = 3400,
  TRANSFER_COMPLETED = 3500,
  TRANSFER_FAILED = 3600,
  CANCEL_PENDING = 6900,
  CANCELLED = 7000,
}
export enum ACCOUNT_TYPES {
  INVESTMENT_ACCOUNT = "Investment Account",
  DEPOSIT_ACCOUNT = "Deposit Account",
  INTEREST_ACCOUNT = "Interest Account",
  EXCHANGE_ACCOUNT = "Exchange Account",
}
